// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvvqxoxzddyoorbgouzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dnF4b3h6ZGR5b29yYmdvdXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODE2ODcsImV4cCI6MjA3MDI1NzY4N30.KFOjy2HbnpF5SygtLvxYUGlA4EQDGwhPB1zx0Kx9ImA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});